import React from 'react';

interface Report {
  reportName: string;
  type: string;
  generatedBy: string;
  generatedDate: string;
  status: 'Completed' | 'Pending' | 'Failed';
}

const mockReports: Report[] = [
  { reportName: 'Revenue Summary', type: 'Financial', generatedBy: 'John Doe', generatedDate: '2026-05-01', status: 'Completed' },
  { reportName: 'User Activity Report', type: 'Analytics', generatedBy: 'John Doe', generatedDate: '2026-05-02', status: 'Completed' },
  { reportName: 'Page Views Report', type: 'Traffic', generatedBy: 'John Doe', generatedDate: '2026-05-03', status: 'Pending' },
  { reportName: 'Session Report', type: 'Analytics', generatedBy: 'John Doe', generatedDate: '2026-05-04', status: 'Completed' },
  { reportName: 'Transaction Report', type: 'Financial', generatedBy: 'John Doe', generatedDate: '2026-05-05', status: 'Failed' },
];

const StatusBadge: React.FC<{ status: Report['status'] }> = ({ status }) => {
  const styles: Record<Report['status'], string> = {
    Completed: 'bg-emerald-400/10 text-emerald-400',
    Pending: 'bg-amber-400/10 text-amber-400',
    Failed: 'bg-rose-400/10 text-rose-400',
  };

  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${styles[status]}`}>
      {status}
    </span>
  );
};

const ReportsPage: React.FC = () => {
  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="flex flex-col gap-1">
        <h1 className="text-3xl font-bold tracking-tight text-white">Reports</h1>
        <p className="text-slate-400">View generated analytics reports</p>
      </div>

      <div className="bg-slate-900/40 border border-slate-800 rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full max-w-full text-left" aria-label="Generated reports">
            <thead>
              <tr className="border-b border-slate-800">
                <th className="px-6 py-4 text-xs font-medium text-slate-400 uppercase tracking-wider">Report Name</th>
                <th className="px-6 py-4 text-xs font-medium text-slate-400 uppercase tracking-wider">Type</th>
                <th className="px-6 py-4 text-xs font-medium text-slate-400 uppercase tracking-wider">Generated By</th>
                <th className="px-6 py-4 text-xs font-medium text-slate-400 uppercase tracking-wider">Generated Date</th>
                <th className="px-6 py-4 text-xs font-medium text-slate-400 uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody>
              {mockReports.map((report) => (
                <tr key={report.reportName} className="border-b border-slate-800 last:border-b-0 hover:bg-slate-800/30 transition-colors">
                  <td className="px-6 py-4 text-sm text-slate-200">{report.reportName}</td>
                  <td className="px-6 py-4 text-sm text-slate-200">{report.type}</td>
                  <td className="px-6 py-4 text-sm text-slate-200">{report.generatedBy}</td>
                  <td className="px-6 py-4 text-sm text-slate-200">{report.generatedDate}</td>
                  <td className="px-6 py-4">
                    <StatusBadge status={report.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;
